// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7B_r8QxEoQBRGTHnQzhNnTstBxV5IUk',
    appId: '1:853556404389:web:58fedfddc5b0c902bd6d4c',
    messagingSenderId: '853556404389',
    projectId: 'bronconest-d1f01',
    authDomain: 'bronconest-d1f01.firebaseapp.com',
    storageBucket: 'bronconest-d1f01.firebasestorage.app',
    measurementId: 'G-TFRY2G9ZC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4nDR7muSPT7UXVgvh8aTvPwGl97a4wu4',
    appId: '1:853556404389:android:a44ee397e38b762bbd6d4c',
    messagingSenderId: '853556404389',
    projectId: 'bronconest-d1f01',
    storageBucket: 'bronconest-d1f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ltQc5FkuzaVlGUW_XAh9wDfVHyJUz_M',
    appId: '1:853556404389:ios:8e1226e8c01a474abd6d4c',
    messagingSenderId: '853556404389',
    projectId: 'bronconest-d1f01',
    storageBucket: 'bronconest-d1f01.firebasestorage.app',
    iosClientId: '853556404389-ppc8e4u60ucm27s9oqr8pch8u7v0l5k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bronconestApp',
  );

}